name: 'Duplicate code detection tool'
description: 'Detect similarities between source code files'
inputs:
  github_token:
    description: 'The GitHub token'
    required: true
  directories:
    description: 'A comma-separated list of the directories containing the source code'
    required: true
  ignore_directories:
    description: 'A comma-separated list of directories that should be ignored'
    required: false
    default: ''
  project_root_dir:
    description: 'The relative path to filter out when reporting results'
    required: false
    default: './'
  file_extensions:
    description: 'A comma-separated list of source code file extensions to check for similarities'
    required: false
    default: 'h, hpp, c, cpp, cc, java, py, cs'
  ignore_below:
    description: 'The minimum similarity percentage to be reported'
    required: false
    default: 10
  fail_above:
    description: 'The maximum allowed similarity percentage before the action fails'
    required: false
    default: 100
  warn_above:
    description: 'The maximum allowed similarity percentage before the action warns'
    required: false
    default: 100
  only_code:
    description: "Removes comments and docstrings from the source code before analysis"
    required: false
    default: false
  one_comment:
    description: 'Duplication report will be left as a single comment, which will be updated, instead of multiple ones'
    required: false
    default: false
  header_message_start:
    description: 'The message to be displayed at the start of the duplication report.
                  It is used by the bot to identify previous reports and update them, so it must be unique.
                  If you want to use the Action in multiple steps of the same workflow,
                  then you can change this message in each step to avoid conflicts'
    required: false
    default: '## 📌 Duplicate code detection tool report'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'check'  
  color: 'green'
